### ISSUE TITLE
Clean up the HitBTC client code

### ISSUE THREAD

**Issue by ackhia** [ackhia/marketmaker-bot#2]
Some of the methods have far to much code and the nesting is too deep

**Comment by m-root** [comment]
Will have a look at it and help you out to simplify it.

**Comment by m-root** [comment]
The huge layers of code are making it a bit slow.

**Comment by ackhia** [comment]
I have just seen your comment. Sorry for the late reply and thanks for taking a look! IIRC HitBTC changed their fee structure as I was completing the bot which made it inviable to run so I ended up giving up on the project. Sorry!
